Update example.jsonld
smart-data-models/incubated pull request #126
Opened 2023-08-01 08:25 UTC by pixelimperiumn1

2023-08-01 15:05 UTC, Fan5Shi reviewed
Don't forget to add "@context" since it's a jsonld file.

In your case, it would be "@context": ["https://raw.githubusercontent.com/smart-data-models/dataModel.TourismDestinations/master/context.jsonld"]

2023-08-02 18:23 UTC, pixelimperiumn1 commented
done =)

2023-08-08 14:51 UTC, albertoabellagarcia requested changes

2023-08-08 14:51 UTC, albertoabellagarcia commented on SmartDestinations/ConsumptionBehaviour/examples/example.jsonld
>  {
This payload is not validated by the schema. the changes properties are wrong types (they are numbers and you quoted as strings"

2023-08-28 10:03 UTC, albertoabellagarcia approved these changes

2023-08-28 10:04 UTC, merged