DIH Data Models
smart-data-models/incubated pull request #69
Opened 2021-12-21 17:02 UTC by manfredipist

2021-12-21 17:34 UTC, albertoabellagarcia requested changes
Thank you very much. It is promising. 
Please attend the comments and update PR

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/ADOPTERS.yaml
> +description: This is a compilation list of the current adopters of the data model [Data model] of the Subject [Subject].  All fields are non mandatory. More info at https://smart-data-models.github.i
it would be good to fill it with the actual values where this data model is being used

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/examples/example-normalized.jsonld
> +{
Option 1) File name is wrong. then you should rename example-nomalized.json and remove @context 
option 2) You should change all the types to Property and keep the name.

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/examples/example.json
> +	"extra": {
Bad idea to have a subproperty named 'properties'

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/notes.yaml
> +notesPrevious:
remove the content of the template.

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/schema.json
> +{
missing 
"modelTags": "",

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/schema.json
> +  "type": "object",
missing the usual $ref.
without them, you have no id for the data model.
Additionally, you have not included the attribute type which is mandatory for the NGSI.

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/examples/example.jsonld
> +{
I have not check that it is validated by the schema. You can do it here https://www.jsonschemavalidator.net/

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/schema.json
> +}
the @ of required attributes is hard to justify. the data models are meant to be used in many other use cases. Why are all of them required? What if there is no attribute value info available. Should we prevent the user to use the data model? 
Ideally only required id and type.

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/ADOPTERS.yaml
> +description: This is a compilation list of the current adopters of the data model [Data model] of the Subject [Subject].  All fields are non mandatory. More info at https://smart-data-models.github.i
fill the template

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/CONTRIBUTORS.yaml
> +description: This is a compilation list of all CONTRIBUTORS across different objects (data models) alphabetically ordered. All fields are non mandatory
contributors file is only available at the subject level. Therefore it should be one level up and only one file.

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/examples/example-normalized.jsonld
> +{
same point as other example. 
Either is a NGSIv2 or NGSI-LD. If you have @context  (NGSI-LD) types are 'Property' , if it is NGSIv2 then it is right but you don't have @context

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/examples/example-normalized.jsonld
> +{
and name it accordingly. See the contribution manual https://bit.ly/contribution_manual

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/examples/example.json
> +	"extra": {
Bad idea subproperty named 'properties' which is a reserved word for json schema

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/examples/example.jsonld
> +{
missing mandatory 'type' attribute

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/notes.yaml
> +notesPrevious:
remove template contents

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/schema.json
> +  "$schema": "http://json-schema.org/schema#",
missing 
"modelTags": "",

2021-12-21 17:34 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/schema.json
> +  "required": [
this required clause is not acceptable unless a very very clear justification. Ideally just id and type

2021-12-22 11:45 UTC, manfredipist commented
@albertoabellagarcia  Fixed applied! Thanks for your help.

2021-12-22 17:17 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/ADOPTERS.yaml
> +description: This is a compilation list of the current adopters of the data model [Data model] of the Subject [Subject].  All fields are non mandatory. More info at https://smart-data-models.github.i
please change the brackets in the first line. ok for the rest

2021-12-22 17:17 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/examples/example-normalized.jsonld
> +	"title": {
cannot be Text but Property

2021-12-22 17:18 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/examples/example.json
> +	"extra": {
But you need a name. As far as I see there is not a name here.

2021-12-22 17:19 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHub/examples/example.jsonld
> +	"extra": {
missing subattribute name

2021-12-22 17:20 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/examples/example.json
> +	"extra": {
you need a name for subproperty

2021-12-22 17:20 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/examples/example.jsonld
> +	"extra": {
need subproperty name

2021-12-22 17:22 UTC, albertoabellagarcia commented on CROSSSECTOR/DIH/DigitalInnovationHubService/schema.json
> +				"extra": {
not much fond of 'open' objects.  (without defined subattributes)
if you do not have anything clear then remove it. (and removed it as well from the examples)
It is not a big deal to add attributes later if necessary.

2021-12-22 17:23 UTC, albertoabellagarcia requested changes
Substantial improvement. But please attend to the new comments.

2021-12-23 09:04 UTC, manfredipist commented
Comments reviewed, thanks again for your help!

2021-12-23 10:05 UTC, albertoabellagarcia approved these changes
It seems right, I'll check the payloads before publishing

2021-12-23 10:06 UTC, merged