Add datamodel.OSLO.PassengerTransportHubs
smart-data-models/incubated pull request #77
Opened 2022-03-31 13:56 UTC by brechtvdv

2022-03-31 14:01 UTC, brechtvdv commented
The caret sign (^) is signed to indicate that a property has been inherited (section 3.2.5 in the OSLO modelling guidelines https://github.com/Informatievlaanderen/OSLO-handleiding/blob/master/Modellering/OSLO-Modelleringsregels.pdf)

2022-04-18 13:25 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/BicycleParkingStationPTH-AP/examples/example-normalized.jsonld
> +{
This relationship is not a property?  I cannot see the link to the entity related to it.

2022-04-18 13:25 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/BicycleParkingStationPTH-AP/examples/example-normalized.jsonld
> +  "geometry": {
same for this 'relationship' I guess this is actually an object.

2022-04-18 13:26 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/BicycleParkingStationPTH-AP/notes.yaml
> +notesHeader:
remove template texts

2022-04-18 13:31 UTC, albertoabellagarcia requested changes
I'd like to see the keyvalues example validated by the schema.json. Please see individual comments

2022-05-17 13:13 UTC, albertoabellagarcia requested changes
Please check comments along files

2022-06-13 12:14 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/context.jsonld
> +{
I need t create something for this especifically

2022-07-13 13:46 UTC, brechtvdv commented
Based on the last working group of the OSLO trajectory "Passenger Transport Hubs", I've updated this data model:

The BicycleParkingStation datamodel only describes the infrastructural part of the station, e.g. how many docks are available.
The ResourceReport datamodel allows to summarize the number of resources that are in a certain state, e.g. the number of available bikes.

2022-07-15 08:30 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/ResourceReportPTH-AP/schema.json
> +        },
missing either properties clause or data type

2022-07-15 08:31 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/ResourceReportPTH-AP/schema.json
> +          "description": "Property. Model:'https://purl.eu/ns/mobility/passenger-transport-hubs#service'. The MobilityService used within the ResourceReport."
This element is not having properties clause?

2022-07-15 08:33 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/BicycleParkingStationPTH-AP/notes.yaml
> +notesHeader:
please remove the templated texts

2022-07-15 08:34 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/ResourceReportPTH-AP/notes.yaml
> +notesHeader:
remove templated texts

2022-08-18 06:56 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/BicycleParkingStationPTH-AP/examples/example-normalized.jsonld
> +{
Have you checked this payload in a context broker ? 
Are you sure it is correct?

2022-08-18 06:57 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/ResourceReportPTH-AP/examples/example-normalized.jsonld
> +{
Have you checked this payload in a context broker?

2022-08-18 07:36 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/context.jsonld
> +{
I have created a customization method for contexts. See the new version of [contribution manual](https://bit.ly/contribution_manual)

2022-08-19 08:32 UTC, albertoabellagarcia commented on dataModel.OSLO.PassengerTransportHubs/context.jsonld
> +{
Already implemented. please see the post on how to do it. create the notes_context.jsonld file [https://smartdatamodels.org/index.php/new-customization-option-for-context/](https://smartdatamodels.org/index.php/new-customization-option-for-context/)

2022-08-25 18:43 UTC, albertoabellagarcia approved these changes
I need to publish it

2022-08-25 18:43 UTC, merged